### ISSUE TITLE
[Bug] bootloop

### ISSUE THREAD

**Issue by chuppito** [Dr-TSNG/Hide-My-Applist#170] opened 2022-08-22 07:30 UTC
### Steps to reproduce/复现步骤

1. Install HMA
2. activate and restart
3. Bootloop

### Expected behaviour/预期行为

I can't test

### Actual behaviour/实际行为

Bootloop 

### Xposed Module List/Xposed 模块列表

```Shell
Pixelify
Lucky Patcher
```

### Magisk Module List/Magisk 模块列表

```Shell
Busybox
Hide my applist
Magiskhide props config
Systemless hots
Universal safetynet fix
Lsosed zygisk
```

### Hide-My-Applist version/Hide-My-Applist 版本

2.3.2

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

26.1.6

### Version requirement/版本要求

- [X] I am using latest debug CI version of Hide-My-Applist and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

impossible to put the log I have to restart in stock, uninstall hide my applist then restart in magisk boot patched

**Comment by cracky5322** [comment] 2022-08-22 07:33
@chuppito Remove HMA Magisk module

**Comment by chuppito** [comment] 2022-08-22 11:38
if i remove the magisk module, the app doesn't work

**Comment by cracky5322** [comment] 2022-08-22 11:40
@chuppito HMA can work normally without modules, please read the information provided in About

**Comment by chuppito** [comment] 2022-08-22 11:44
I read correctly, but I have the message "system service stopped"

![Screenshot_20220822-134308](https://user-images.githubusercontent.com/10908251/185913421-d9e108a8-384c-41e2-8014-cc451b6c7170.png)

**Comment by cracky5322** [comment] 2022-08-22 11:46
@chuppito Maybe you should enter the settings to watch, there are relevant solutions to choose and solve

**Comment by chuppito** [comment] 2022-08-22 11:54
I stopped the services and started.  Since it didn't work, I cleaned and restarted.  Still no service

![Screenshot_20220822-135246](https://user-images.githubusercontent.com/10908251/185915267-99c57726-3435-4011-a06b-821474a7fbdf.png)

**Comment by cracky5322** [comment] 2022-08-22 12:00
@chuppito OK, maybe some features are not working after Android 13, maybe you can try to install the [CI version](https://github.com/Dr-TSNG/Hide-My-Applist/actions), but there is no guarantee that it will work

**Comment by chuppito** [comment] 2022-08-22 12:17
I tried the last and the penultimate version.  I don't understand for the CI version.  I could read that there was the same problem as me on Android 13. Maybe wait for a new version.  thank you

**Comment by cracky5322** [comment] 2022-08-22 12:27
@chuppito Waiting for the developer to have time may ask you to provide logs for judgment
Thank you for your patience

**Comment by DavidBerdik** [comment] 2022-08-23 02:22
I think this issue is the same as https://github.com/Dr-TSNG/Hide-My-Applist/issues/168.

**Comment by Dr-TSNG** [comment] 2022-08-23 03:02
duplicate of #168

**Closed by Dr-TSNG** 2022-08-23 03:02 UTC
Labels: bug, duplicate
