### ISSUE TITLE
App native crash

### ISSUE THREAD

**Issue by skrimix** [Dr-TSNG/Hide-My-Applist#23] opened 2021-05-13 14:29 UTC
Apps are crashing in native on launch when both "File detection" hide method and "Reject applist requests" are enabled. This happens with any app.

Device info:
Name: Xiaomi Redmi Note 8 Pro
ROM: Android 11 POSP (AOSP-based custom)
LSPosed version: v1.3.5 (5616) CI build
Hide My Applist version: 1.5.4.Native

Crash log:
```
Build fingerprint: 'google/sunfish/sunfish:11/RQ2A.210505.002/7246365:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2021-05-13 18:55:54+0500
pid: 26048, tid: 26119, name: RenderThread  >>> ru.dublgis.dgismobile <<<
uid: 10154
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'FORTIFY: fileno: null FILE*'
    x0  0000000000000000  x1  0000000000006607  x2  0000000000000006  x3  0000007034540e10
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000000020
    x8  00000000000000f0  x9  6fd1f44b43ae91c2  x10 0000000000000000  x11 ffffffc0fffffbdf
    x12 0000000000000001  x13 ffffffff9f63a242  x14 00000070345408f8  x15 ffffffffffffffff
    x16 000000734f487c80  x17 000000734f469870  x18 0000007033a88000  x19 00000000000065c0
    x20 0000000000006607  x21 00000000ffffffff  x22 0000007034543000  x23 0000007034541528
    x24 0000000000000000  x25 0000007034543000  x26 00000070a1899508  x27 00000000000fc000
    x28 000000703444a000  x29 0000007034540e90
    lr  000000734f41d2a0  sp  0000007034540df0  pc  000000734f41d2cc  pst 0000000000001000

backtrace:
      #00 pc 000000000004e2cc  /apex/com.android.runtime/lib64/bionic/libc.so!libc.so (offset 0x4e000) (abort+164) (BuildId: fa5aca5ec290be134916b0e63351ef91)
      #01 pc 0000000000076904  /apex/com.android.runtime/lib64/bionic/libc.so!libc.so (offset 0x61000) (__fortify_fatal(char const*, ...)+124) (BuildId: fa5aca5ec290be134916b0e63351ef91)
      #02 pc 00000000000a8434  /apex/com.android.runtime/lib64/bionic/libc.so!libc.so (offset 0x61000) (fileno+116) (BuildId: fa5aca5ec290be134916b0e63351ef91)
      #03 pc 0000000000efde40  /vendor/lib64/egl/libGLES_mali.so (BuildId: 235c504dda87aae526f020d91bdc4f3a)
      #04 pc 0000000000ef58e4  /vendor/lib64/egl/libGLES_mali.so (BuildId: 235c504dda87aae526f020d91bdc4f3a)
      #05 pc 0000000000ef5874  /vendor/lib64/egl/libGLES_mali.so (BuildId: 235c504dda87aae526f020d91bdc4f3a)
      #06 pc 0000000000ef66a0  /vendor/lib64/egl/libGLES_mali.so (BuildId: 235c504dda87aae526f020d91bdc4f3a)
      #07 pc 0000000000ef7084  /vendor/lib64/egl/libGLES_mali.so (BuildId: 235c504dda87aae526f020d91bdc4f3a)
      #08 pc 0000000000a0c240  /vendor/lib64/egl/libGLES_mali.so (BuildId: 235c504dda87aae526f020d91bdc4f3a)
      #09 pc 0000000000a0c608  /vendor/lib64/egl/libGLES_mali.so (BuildId: 235c504dda87aae526f020d91bdc4f3a)
      #10 pc 0000000000a40fd4  /vendor/lib64/egl/libGLES_mali.so (eglInitialize+140) (BuildId: 235c504dda87aae526f020d91bdc4f3a)
      #11 pc 00000000000148cc  /system/lib64/libEGL.so (android::egl_display_t::initialize(int*, int*)+296) (BuildId: 6b2a1587bbda3dff7811f0e35d160add)
      #12 pc 0000000000220c84  /system/lib64/libhwui.so (android::uirenderer::renderthread::EglManager::initialize()+84) (BuildId: 4affcf0e60fed57ab3048a5b65ce6502)
      #13 pc 000000000022f7d4  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::requireGlContext()+84) (BuildId: 4affcf0e60fed57ab3048a5b65ce6502)
      #14 pc 0000000000215680  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::setSurface(ANativeWindow*, android::uirenderer::renderthread::SwapBehavior)+88) (BuildId: 4affcf0e60fed57ab3048a5b65ce6502)
      #15 pc 000000000021d14c  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::setSurface(ANativeWindow*, bool)+368) (BuildId: 4affcf0e60fed57ab3048a5b65ce6502)
      #16 pc 000000000022c9ec  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread11RenderProxy10setSurfaceEP13ANativeWindowbE3$_6NS_9allocatorIS8_EEFvvEEclEv$81825b4554ba48924a771fcb836d7698+28) (BuildId: 4affcf0e60fed57ab3048a5b65ce6502)
      #17 pc 000000000020ed94  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+220) (BuildId: 4affcf0e60fed57ab3048a5b65ce6502)
      #18 pc 000000000023001c  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+88) (BuildId: 4affcf0e60fed57ab3048a5b65ce6502)
      #19 pc 00000000000154d0  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+260) (BuildId: ceae7b3f2b98c0819dea4df81964a864)
      #20 pc 0000000000014d94  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+412) (BuildId: ceae7b3f2b98c0819dea4df81964a864)
      #21 pc 00000000000afd4c  /apex/com.android.runtime/lib64/bionic/libc.so!libc.so (offset 0x61000) (__pthread_start(void*)+64) (BuildId: fa5aca5ec290be134916b0e63351ef91)
      #22 pc 0000000000050288  /apex/com.android.runtime/lib64/bionic/libc.so!libc.so (offset 0x4f000) (__start_thread+64) (BuildId: fa5aca5ec290be134916b0e63351ef91)
```
Full tombstone: https://del.dog/lopyretilo

**Comment by Dr-TSNG** [comment] 2021-05-13 14:55
Native crashes are caused by unstability of upstream library Dobby. I can do nothing but wait for its maintainers to fix this. But if the non-native version crashes too, please provide more logs.

**Comment by skrimix** [comment] 2021-05-13 15:18
Okay, I will try non-native version. I saw about issues with Dobby, but decided to report as this doesn't happen when some apps are hidden, only when all.

**Comment by Dr-TSNG** [comment] 2021-05-30 03:07
Should have fixed in the new stable version, close the issue if solved

**Closed** 2021-06-04 09:27 UTC
Labels: bug
